server:
  port: 8082

spring:
  application:
    name: posts-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/redperi}
    username: ${SPRING_DATASOURCE_USERNAME:redperi}
    password: ${SPRING_DATASOURCE_PASSWORD:redperi123}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET:estaEsUnaClaveSecretaMuyLargaParaFirmarLosTokensJWT1234567890}

springdoc:
  swagger-ui:
    path: /docs
